### PR TITLE
Fixed a bug related to child_add due to changeMap using in, out and expe...

### PR DESCRIPTION
**Pull request by CurtisHumphrey**
...cting to use added, removed

### CODE REVIEW

**Comment by bendrucker** [comment]
Can you add a failing test here?

**Comment by bendrucker** [comment]
Or even just describe something you were trying to do that was broken and I'll commit the test

**Comment by CurtisHumphrey** [comment]
I found it when I subscribing to a 'child add' event instead of a once 'value' event. When I pushed a new value later it did not update because handleRefEvent function expect change map to have keys added and removed and the function originally returned in and out. Do you still need a test or do you see it from inspection?

**Comment by bendrucker** [comment]
Would be helpful to see a test so I can be sure I'm fixing it

**Comment by CurtisHumphrey** [comment]
I'm working on one but at this point I have not be able to reproduce it outside of my code base. I could create a simple test to check that changeMap returns an object with keys "added" and "removed" if you want.

**Comment by bendrucker** [comment]
Ideally I'd like to see something that only calls the public API

**Comment by CurtisHumphrey** [comment]
By inspection you can see that "_.each(map.added, function (addKey) {
        self.fakeEvent('child_added', newSnap.child(addKey));
      });
      _.each(map.removed, function (remKey) {
        self.fakeEvent('child_removed', oldSnap.child(remKey));
      });" will never work without changeMap returning the correct object structure.

**Comment by CurtisHumphrey** [comment]
Got it. Post coming soon.

**Comment by CurtisHumphrey** [comment]
So it happen with some interplay of the startAt. Test uses all the public APIs.

**Comment by CurtisHumphrey** [comment]
Do you need anything else to incorporate this change?

**Comment by bendrucker** [comment]
Thanks for the reminder

**Comment by CurtisHumphrey** [comment]
Thanks!

**Comment by bendrucker** [comment]
Sure — thank you!

**Pull request closed without merging**
